scalar JSON

type Transport {
  userId: String!
  data: JSON!
}

input SendDataInput {
  channelId: String!
  userId: String!
  data: JSON!
}

input ChannelInput {
  channelId: String!
  userId: String!
}

type Query {
  transportUserCount(channelId: String!): Int
  transportHistory(channelId: String!): [Transport!]
}

type Mutation {
  sendData(input: SendDataInput!): Boolean!
  enterChannel(input: ChannelInput!): Boolean!
  exitChannel(input: ChannelInput!): Boolean!
}

type Subscription {
  transport(channelId: String!): Transport!
}
